/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactImport } from './routes/contact'
import { Route as notFoundRouteImport } from './routes/__notFoundRoute'
import { Route as IndexImport } from './routes/index'
import { Route as BlogsIndexImport } from './routes/blogs/index'
import { Route as BlogsBlogIdImport } from './routes/blogs/$blogId'

// Create/Update Routes

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const notFoundRouteRoute = notFoundRouteImport.update({
  id: '/__notFoundRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogsIndexRoute = BlogsIndexImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRoute,
} as any)

const BlogsBlogIdRoute = BlogsBlogIdImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__notFoundRoute': {
      id: '/__notFoundRoute'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof notFoundRouteImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdImport
      parentRoute: typeof rootRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof notFoundRouteRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs': typeof BlogsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof notFoundRouteRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs': typeof BlogsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__notFoundRoute': typeof notFoundRouteRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs/': typeof BlogsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/contact' | '/blogs/$blogId' | '/blogs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/contact' | '/blogs/$blogId' | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/__notFoundRoute'
    | '/contact'
    | '/blogs/$blogId'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  notFoundRouteRoute: typeof notFoundRouteRoute
  ContactRoute: typeof ContactRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  notFoundRouteRoute: notFoundRouteRoute,
  ContactRoute: ContactRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/__notFoundRoute",
        "/contact",
        "/blogs/$blogId",
        "/blogs/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/__notFoundRoute": {
      "filePath": "__notFoundRoute.jsx"
    },
    "/contact": {
      "filePath": "contact.jsx"
    },
    "/blogs/$blogId": {
      "filePath": "blogs/$blogId.jsx"
    },
    "/blogs/": {
      "filePath": "blogs/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
