/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactImport } from './routes/contact'
import { Route as notFoundRouteImport } from './routes/__notFoundRoute'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as BlogsIndexImport } from './routes/blogs/index'
import { Route as BlogsCreateImport } from './routes/blogs/create'
import { Route as BlogsBlogIdImport } from './routes/blogs/$blogId'
import { Route as BlogsEditBlogIdImport } from './routes/blogs/edit/$blogId'

// Create/Update Routes

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const notFoundRouteRoute = notFoundRouteImport.update({
  id: '/__notFoundRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const BlogsIndexRoute = BlogsIndexImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRoute,
} as any)

const BlogsCreateRoute = BlogsCreateImport.update({
  id: '/blogs/create',
  path: '/blogs/create',
  getParentRoute: () => rootRoute,
} as any)

const BlogsBlogIdRoute = BlogsBlogIdImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRoute,
} as any)

const BlogsEditBlogIdRoute = BlogsEditBlogIdImport.update({
  id: '/blogs/edit/$blogId',
  path: '/blogs/edit/$blogId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__notFoundRoute': {
      id: '/__notFoundRoute'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof notFoundRouteImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdImport
      parentRoute: typeof rootRoute
    }
    '/blogs/create': {
      id: '/blogs/create'
      path: '/blogs/create'
      fullPath: '/blogs/create'
      preLoaderRoute: typeof BlogsCreateImport
      parentRoute: typeof rootRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/blogs/edit/$blogId': {
      id: '/blogs/edit/$blogId'
      path: '/blogs/edit/$blogId'
      fullPath: '/blogs/edit/$blogId'
      preLoaderRoute: typeof BlogsEditBlogIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof notFoundRouteRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs/create': typeof BlogsCreateRoute
  '/blogs': typeof BlogsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/blogs/edit/$blogId': typeof BlogsEditBlogIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof notFoundRouteRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs/create': typeof BlogsCreateRoute
  '/blogs': typeof BlogsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/blogs/edit/$blogId': typeof BlogsEditBlogIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__notFoundRoute': typeof notFoundRouteRoute
  '/contact': typeof ContactRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs/create': typeof BlogsCreateRoute
  '/blogs/': typeof BlogsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/blogs/edit/$blogId': typeof BlogsEditBlogIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/contact'
    | '/blogs/$blogId'
    | '/blogs/create'
    | '/blogs'
    | '/projects'
    | '/blogs/edit/$blogId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/contact'
    | '/blogs/$blogId'
    | '/blogs/create'
    | '/blogs'
    | '/projects'
    | '/blogs/edit/$blogId'
  id:
    | '__root__'
    | '/'
    | '/__notFoundRoute'
    | '/contact'
    | '/blogs/$blogId'
    | '/blogs/create'
    | '/blogs/'
    | '/projects/'
    | '/blogs/edit/$blogId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  notFoundRouteRoute: typeof notFoundRouteRoute
  ContactRoute: typeof ContactRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  BlogsCreateRoute: typeof BlogsCreateRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  BlogsEditBlogIdRoute: typeof BlogsEditBlogIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  notFoundRouteRoute: notFoundRouteRoute,
  ContactRoute: ContactRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  BlogsCreateRoute: BlogsCreateRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  BlogsEditBlogIdRoute: BlogsEditBlogIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/__notFoundRoute",
        "/contact",
        "/blogs/$blogId",
        "/blogs/create",
        "/blogs/",
        "/projects/",
        "/blogs/edit/$blogId"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/__notFoundRoute": {
      "filePath": "__notFoundRoute.jsx"
    },
    "/contact": {
      "filePath": "contact.jsx"
    },
    "/blogs/$blogId": {
      "filePath": "blogs/$blogId.jsx"
    },
    "/blogs/create": {
      "filePath": "blogs/create.jsx"
    },
    "/blogs/": {
      "filePath": "blogs/index.jsx"
    },
    "/projects/": {
      "filePath": "projects/index.jsx"
    },
    "/blogs/edit/$blogId": {
      "filePath": "blogs/edit/$blogId.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
